export const HERO = Object.freeze({
  EYEBROW:  'Για την καθημερινότητά σου',
  TITLE:    'Ό,τι χρειάζεσαι.',
  TITLE_EM: 'Πριν καν το ψάξεις στο Google.',
  SUBTITLE: 'Ένα portal. Πέντε υπηρεσίες. Ο χρόνος σου πιάνει τόπο.',
  STATS: Object.freeze([
    { value: 5,   label: 'Υπηρεσίες',          suffix: '' },
    { value: 100, label: 'Δωρεάν',              suffix: '%' },
    { value: 0,   label: 'Χωρίς λογαριασμό',   suffix: '' },
  ]),
});

export const SERVICES = Object.freeze([
  {
    id:          'molis-tora',
    slug:        'molis-tora',
    name:        'Μόλις\nΤώρα',
    shortName:   'Μόλις Τώρα',
    category:    'Ειδήσεις · Real-time',
    description: 'Δες όλες τις ειδήσεις, χωρίς κλικ.',
    bg:          '#f5c842',
    color:       '#3a2800',
    subColor:    '#7a5800',
    arrowColor:  '#5a3c00',
    icon:        '📰',
    iconBg:      '#e8a800',
    monogram:    'MT',
    href:        '/molis-tora',
    gridArea:    'molis',
    size:        'large',
    isNew:       false,
    comingSoon:  false,
    highlight:   false,
    visuals: {
      hoverEffect:     'lift',
      gradientOverlay: 'rgba(0,0,0,0.06)',
    },
  },
  {
    id:          'govfast',
    slug:        'govfast',
    name:        'GovFast',
    shortName:   'GovFast',
    category:    'Δημόσιο · Έγγραφα',
    description: 'Βρες δημόσια έγγραφα σε δευτερόλεπτα.',
    bg:          '#0D5EAF',
    color:       '#ffffff',
    subColor:    '#a8c8f0',
    arrowColor:  '#a8c8f0',
    icon:        '🏛',
    iconBg:      '#0a4a8a',
    monogram:    'GF',
    href:        '/govfast',
    gridArea:    'gov',
    size:        'normal',
    isNew:       false,
    comingSoon:  false,
    highlight:   false,
    visuals: {
      hoverEffect:     'lift',
      gradientOverlay: 'rgba(0,0,0,0.08)',
    },
  },
  {
    id:          'fastbuy',
    slug:        'fastbuy',
    name:        'FastBuy',
    shortName:   'FastBuy',
    category:    'Αγορές · Προτάσεις τιμών',
    description: 'Πάρε έξυπνες προτάσεις αγορών.',
    bg:          '#5a2d9e',
    color:       '#ffffff',
    subColor:    '#c9a8f0',
    arrowColor:  '#c9a8f0',
    icon:        '🛒',
    iconBg:      '#451f7a',
    monogram:    'FB',
    href:        '/fastbuy',
    gridArea:    'buy',
    size:        'normal',
    isNew:       false,
    comingSoon:  false,
    highlight:   false,
    visuals: {
      hoverEffect:     'lift',
      gradientOverlay: 'rgba(0,0,0,0.08)',
    },
  },
  {
    id:          'video-summary',
    slug:        'video-summary',
    name:        'Video & PDF\nSummary',
    shortName:   'Video & PDF',
    category:    'YouTube · PDF · AI',
    description: 'Η ουσία κάθε βίντεο και PDF σε δευτερόλεπτα.',
    bg:          '#e8380d',
    color:       '#ffffff',
    subColor:    '#ffb8a0',
    arrowColor:  '#ffb8a0',
    icon:        '🎬',
    iconBg:      '#b82a09',
    monogram:    'VS',
    href:        '/video-summary',
    gridArea:    'video',
    size:        'small',
    isNew:       false,
    comingSoon:  false,
    highlight:   false,
    visuals: {
      hoverEffect:     'lift',
      gradientOverlay: 'rgba(0,0,0,0.08)',
    },
  },
  {
    id:          'fthinatora',
    slug:        'fthinatora',
    name:        'Φθηνά\nΤώρα',
    shortName:   'Φθηνά Τώρα',
    category:    'Σούπερ μάρκετ · Τιμές',
    description: 'Σύγκριση τιμών σε 7 αλυσίδες + Ευρώπη.',
    bg:          '#1a7a4a',
    color:       '#ffffff',
    subColor:    '#7fe0aa',
    arrowColor:  '#7fe0aa',
    icon:        '💰',
    iconBg:      '#145c37',
    monogram:    'ΦΤ',
    href:        '/fthinatora',
    gridArea:    'fthinatora',
    size:        'full',
    isNew:       false,
    comingSoon:  true,
    highlight:   true,
    visuals: {
      hoverEffect:     'lift',
      gradientOverlay: 'rgba(0,0,0,0.06)',
    },
  },
]);

export const TOKENS = Object.freeze({
  border: {
    width: 4,
    color: '#111',
  },
  animation: {
    ease:     'cubic-bezier(.22,1,.36,1)',
    stagger:  60,
    duration: 550,
  },
  shadow: {
    hover: '8px 8px 0px #111',
    card:  '0 4px 24px rgba(0,0,0,0.08)',
  },
});

export const UI = Object.freeze({ HERO, SERVICES, TOKENS });